
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";
use accapp;

CREATE TABLE `USERS` (
  `USER_ID` int(11) NOT NULL,
  `FIRSTNAME` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `LASTNAME` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `USERNAME` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `EMAIL` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `PHONE` varchar(18) COLLATE utf8_unicode_ci DEFAULT NULL,
  `PASSWORD` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `USERS`
--

INSERT INTO `USERS` (`USER_ID`, `FIRSTNAME`, `LASTNAME`, `USERNAME`, `EMAIL`, `PHONE`, `PASSWORD`) VALUES
(1, 'GIRIDHER', 'SADINENI', 'GIRIDHER', 'giridher@skillverse.in', '9676211990', 'giridhersadineni'),
(2, 'giridher', 'SADINENI', 'giridher', 'GIRIDHER@HOTMAIL.COM', '9676211990', 'giridher');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `USERS`
--
ALTER TABLE `USERS`
  ADD PRIMARY KEY (`USER_ID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `USERS`
--
ALTER TABLE `USERS`
  MODIFY `USER_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;


